SUPABASE_URL = "https://epyevwlxnwmiwgahbbkj.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVweWV2d2x4bndtaXdnYWhiYmtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg3MzQ0OTYsImV4cCI6MjEwNDMxMDQ5Nn0.TEpaf5Vb2SauVHxZu4GKVp3zdhBMlRb88bfX5iCoQFA"
